accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns=[
    path('signup/',
         views.SignUpView.as_view(),
         name='signup'),

    path('signup_success/',
         views.SignUpSuccessView.as_view(),
         name='signup_success'),

]

myprotein/urls.py
from django.contrib import admin
from django.urls import path, include #include追加
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('photo.urls')),


    path('', include('accounts.urls')),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from . import views

app_name = 'photo'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreatePhotoView.as_view(), name = 'post'),
  
    path('post_done/',
         views.PostSuccessView.as_view(),
         name = 'post_done'),
    path('photos/<int:category>',
         views.CategoryView.as_view(),
         name = 'photos_cat'
         ),

    path('user-list/<int:user>',
         views.UserView.as_view(),
         name = 'user_list'
         ),

    path('photo-detail/<int:pk>',
         views.DetailView.as_view(),
         name = 'photo_detail'
         ),

    path('mypage/', views.MypageView.as_view(), name = 'mypage'),

    path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
         ),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    pass

accouts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    
    pass

photo/models.py
from django.db import models
#accountsアプリのmodelsモジュールからCuatomUserをインポート
# Create your models here.
from accounts.models import CustomUser

class Category(models.Model):
    #投稿する写真のカテゴリを管理するモデル

    #カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ'#フィールドのタイトル
        max_length=20)

def __str__(self):
    #オブジェクトを文字列に変換して返す
    #eturns(str):カテゴリ名
    return self.title

class PhotoPost(models.Model):
    # 投稿されたデータを管理するモデル
    # CustomUserモデルのuser_idとPhotoPostモデルを1対多の関係で結びつける
    # CustomUserが親でPhotoPostが子の関係になる
    user = models.ForeignKey(
        CustomUser,
        #フィールドのタイトル
        verbose_name='ユーザー',
        #ユーザーを削除する場合はそのユーザーの投稿データも全て削除する
        on_delete=models.CASCADE
        )
    #categoryモデルのtitleとPhotoPostモデルを1対多の関係で結びつける
    # categoryが親でPhotoPostが子の関係になる
    category = models.ForeignKey(
        Category,
        #フィールドのタイトル
        verbose_name='カテゴリ'
        #カテゴリに関連付けられた投稿データが存在する場合はそのカテゴリを削除できないようにする
        on_delete=models.PROTECT
        )
#タイトル用フィールド
title = models.CharField(
    verbose_name='タイトル', #フィールドのタイトル
    max_length=200           #最大文字数は200
    )
#コメント用のフィールド
comment = models.TextField(
    verbose_name='コメント', #フィールドのタイトル
    )
#イメージのフィールド１
image1 = models.ImageField(
    verbose_name='イメージ１', #フィールドのタイトル
    upload_to = 'photos', #media_poot以下のphotosにファイルを保存
    )
#イメージのフィールド２
image2 = models.ImageField(
    verbose_name='イメージ2', #フィールドのタイトル
    upload_to = 'photos', #media_poot以下のphotosにファイルを保存
    blank = True, #フィールド値の設定は必須ではない
    null = True #データベースにnullが保存されることを許容
    )
#投稿日時のフィールド
posted_at=models.DateTimeField(
    verbose_name='投稿日時'#フィールドのタイトル
    auto_now_add=True     #日時を自動追加
    )

def __str__(self):
    # オブジェクトを文字列に変換して返す
    # returns(str):投稿記事のタイトル
    return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
          model=CustomUser
          field=('username','email','password1','password2')

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):

    class Meta:

        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class=CustomUserCreationForm
    template_name="signup.html"
    success_url=reverse_lazy('accounts:signup_success')

    def form_vail(self,form):
        user=form.save()
        self.object=user
        return super().form_valid(form)
    
class SignUpSuccessView(TemplateView):
    template_name="signup_success.html"

photo/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView, ListView

from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import PhotoPostForm

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required

from .models import PhotoPost

from django.views.generic import DetailView

from django.views.generic import DeleteView

class IndexView(ListView):

    template_name = 'index.html'

    queryset = PhotoPost.objects.order_by('-posted_at')

    pagenate_by = 15


@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):


    form_class = PhotoPostForm

    template_name = "post_photo.html"

    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form):


        postdata = form.save(commit=False)

        postdata.user = self.request.user

        postdata.save()

        return super().form_valid(form)
    
class PostSuccessView(TemplateView):

    template_name = 'post_success.html'

class UserView(ListView):

    template_name ='index.html'

    paginate_by = 15

    def get_queryset(self):

        user_id = self.kwargs['user']
        user_list = PhotoPost.objents.filter(
            user=user_id).order_by('-posted_at')
        return user_list
    
class DetailView(DetailView):

    template_name ='detail.html'

    model = PhotoPost

class MypageView(ListView):

    template_name ='mypage.html'

    paginate_by 15

    def get_queryset(self):

        queryset = PhotoPost.object.filter(
            user=self.request.user).order_by('-poster_at')
        return queryset
    
class PhotoDeleteView(DeleteView):

    model = PhotoPost

    template_name ='photo_delete.html'

    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):

        return super().delete(request, *args, **kwargs)

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{% block title %}{% endblock %}</title>   

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">お気に入りを見つけよう</h4>
          <p class="text-muted">
            誰でも参加できる写真投稿サイトです
            自分で撮影した写真ならなんでもオーケー！
            でも、カテゴリに属する写真に限ります。
            コメントもつけてください！
          </p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Contact</h4>
          <ul class="list-unstyled">

            {% if user.is_authenticated %}
            <li><a href="{% url 'photo:mypage' %}"
                   class="text-white">マイページ</a></li>
            <li><a href="{% url 'accounts:logout' %}"
                   class="text-white">ログアウト</a></li>
            <li><a href="{% url 'password_reset' %}"
                   class="text-white">パスワードのリセット</a></li>
            <li><a href="mailto:admin@example.com"
                   class="text-white">Email me</a></li>
            {% else %}

            <li><a href="{% url 'accounts:signup' %}"
                   class="text-white">サインアップ</a></li>
            <li><a href="{% url 'accounts:login' %}" 
                   class="text-white">ログイン</a></li>
            <li><a href="mailto:admin@example.com"
                   class="text-white">Email me</a></li>
            {% endif %}


          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'photo:index' %}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Photo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
  
  {% block contents %}{% endblock %}
</main>

<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please a lot!</p>
  </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      
  </body>
</html>

photo/templates/detail.html
{% extends 'base.html' %}

{% block title %}Photo Detail{% endblock %}

    {% block contents %}

    <br>
    <div class="container">

        <div class="row">

            <div class="col offset-3">

                <h2>{{objent.title}}</h2>

                <p>{{objent.comment}}</p>
                <br>

                <p>{{objent.poster_at}}に投稿</p>

                <p><img src="{{ objent.image1.url }}"></img></p>

                {% if object.image2 %}
                    <p><img src="{{ objent.image2.url }}"></img></p>
                {% endif %}
                
                {% if request.user == object.user %}
                <form method="POST">

                <a href="{% url 'photo:photo_delete' object.pk %}"
                    class="btn btn-primary my-2">削除する</a>
                {% endif %}

            </div>
        </div>
    </div>
    {% endblock %}

photo/templates/index.html
{% extends 'base.html' %}

{% block title %}Photo Gallery{% endblock %}

    {% block contents %}

    {% include "photos_title.html" %}

    {% include "photos_list.html" %}

    {% include "pagenation.html" %}

    {% endblock %}

photo/templates/mypage.html
{% extends 'base.html' %}

{% block title %}Mypage{% endblock %}

    {% block contents %}

    {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
            <h4>{{user.username}}さんのマイページ</h4>
            {% if object_list.count == 0 %}
                <p>{{user.username}}さんの投稿はありません</p>
            {% else %}
                <p>投稿<strong>{{objent_list.count}}</strong>件</p>
            {% endif %}
            <a href="{% url 'photo:post' %}">投稿する</a>
        </div>
        <hr>
    {% endif %}

    {% include "photos_list.html" %}

    {% include "pagination.html" %}

    {% endblock%}

photo/templates/pagination.html
<ul class="pagination" style="justify-content:center">
    {% if page_obj.has_previous %}

    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.has_previous_page_number }}"
            aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}

        <li class="page-item antive">
            <span class="page-link">{{ num }}</span>
        </li>

        {% else %}

        <li class="page-item">
            <a class="page-link" herf="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}

    <li class="page-item">
        <a class="page-link"
            href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>

photo/templates/photo_delete.html
{% extends 'base.html'%}

{% block title %}Photo Detail{% endblock %}

    {% block contents %}

    <br>
    <div class="container">
        <div class="row">
            <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除してもいいですか?</p>
                    {% csrf_token %}
                    <button class="btn btn-primary my-2"
                            type="submit">削除</button>
                    <a href="{% url 'photo:photo_detail' object.pk %}"
                       class="btn btn-secondary my-2">キャンセル</a>
            </div>
        </div>
    </div>
    {% endblock %}
        

            

photo/templates/photos_list.html
  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>

            <div class="card-body">
              <p class="card-text"> {{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">{{record.category.title}}</button>
                </div>

                <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-muted"> {{record.user.username}} </small>
                </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

photo/templates/photos_title.html
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">photo Gallery</h1>
        <p class="lead text-muted">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています！
        </p>
        <p>
          {% if user.is_authenticated %}
            <a href="{% url 'photo:post' %}"
              class="btn btn-primary my-2">投稿する</a>
            <a herf="{% url 'accounts:logout' %}"
              class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
            <a href="{% url 'accounts:signup' %}"
              class="btn btn-primary my-2">今すぐサインアップ</a>
            <a href="{% url 'accounts:login' %}"
              class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="#" class="btn btn-secondary my-2">登録済みの方はログイン</a>
        </p>
      </div>
    </div>
  </section> 

photo/templates/post_photo.html
{% extends 'base.html' %}

{% block title %}Post{% endblock%}

    {% block contents %}

    <br>
    <div class="container">

        <div class="row">

            <div class="col offset-2">

                <form method="POST"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tr>
                            <th>カテゴリ</th>
                            <td>{{ form.category }}</td>
                        </tr>
                        <tr>
                            <th>タイトル</th>
                            <td>{{ form.title }}</td>
                        </tr>
                        <tr>
                            <th>コメント</th>
                            <td>{{ form.comment }}</td>
                        </tr>
                        <tr>
                            <th>画像1</th>
                            <td>{{ form.imagel }}</td>
                        </tr>
                        <tr>
                            <th>画像2</th>
                            <td>{{ form.image2 }}</td>
                        </tr>
                    </table>
                    <hr>
                    <button type="submit">投稿する</button>
                </form>
            </dv>
        </dv>
    </dv>
    {% endblock %}

photo/templates/post_success.html
{% extends 'base.html' %}

{% block title %}Post Success{% endblock %}

    {% block contents %}

    <br><br>
    <div class="container">

        <div class="row">

            <div class="col offset-2">
                <h4>投稿が完了しました!</h4>
            </dv>
        </dv>
    </dv>
    {% endblock%}

photo/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method ="post">
                    {% csrf_token %}
                    {% for field in form %}
                    <p>
                        {{field.label_tag}}<br>
                        {{field}}
                        {% if field.help_text %}
                        <small style="color:grey">{{field.help_text}}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p style="coler:red">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                        <p style="color:red">
                            ※メールアドレスはパスワードをリセットする際に必要になりますので、登録をお願いします。
                        </p>
                        <input type="submit" value="Sign up">
                    </form>
                    <br>
                    <p><a href="{% url 'photo:index' %}">
                        登録をやめてトップページに戻る</a>
                    </p>
                </div>
            </div>
        </div>
    {% endblock %}

photo/templates/signup_success.html
{% extends 'base.html' %}
{% block title %}Registration Complete{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="col offset-4 py-4">
            <h3>登録が完了しました</h3>
            <p><a href="#">ログインはこちら</a><p>
            </div>
        </div>
    </div>
    {% endblock %}